### ISSUE TITLE
New mail from template loses To: and Reply-To:

### ISSUE THREAD

**Issue by maffe** [nattoheaven/macrotemplate#3]
When this extension is enabled, a mail created from a template does not have the To: and Reply-To: fields set which are present in the template (the Reply-To: is also defined in the account settings).

**Comment by nattoheaven** [comment]
Thank you for your report.

I think this bug was fixed at version 3.0.0.2.

**Comment by maffe** [comment]
3.0.0.2 works fine indeed. Thank you for the quick fix!
